FROM tiangolo/uvicorn-gunicorn:python3.11-slim

RUN apt-get update && apt-get install -y netcat

# Set the module name to app.main instead of main
ENV MODULE_NAME=app.main

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .